# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_Tutorial.ipynb.

# %% auto 0
__all__ = ['prompt', 'get_result', 'llm_chain']

# %% ../nbs/00_Tutorial.ipynb 2
from langchain.llms import OpenAI

# %% ../nbs/00_Tutorial.ipynb 3
def get_result(text: str) -> str:
    llm = OpenAI(temperature=0.9, verbose=True)
    return llm(text)

# %% ../nbs/00_Tutorial.ipynb 6
from langchain.prompts import PromptTemplate

# %% ../nbs/00_Tutorial.ipynb 7
prompt = PromptTemplate(
    input_variables=["product"],
    template="What is a good name for a company that makes {product}?",
)

# %% ../nbs/00_Tutorial.ipynb 10
from langchain.chains import LLMChain

# %% ../nbs/00_Tutorial.ipynb 11
def _get_llm_and_prompt():
    llm = OpenAI(temperature=0.9)
    prompt = PromptTemplate(
        input_variables=["product"],
        template="What is a good name for a company that makes {product}?",
    )
    return llm , prompt

def llm_chain(user_input):
    llm, prompt = _get_llm_and_prompt()
    chain = LLMChain(llm=llm, prompt=prompt)
    return chain.run(user_input)
