# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm-playground',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/llm-playground',
                'lib_path': 'llm_playground'},
  'syms': {'llm_playground.core': {'llm_playground.core.foo': ('core.html#foo', 'llm_playground/core.py')}}}
